# Generated by Django 2.1.5 on 2019-01-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check_piont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divice_num', models.IntegerField(default=0)),
                ('postal_code', models.CharField(max_length=200)),
                ('place_name', models.CharField(max_length=200)),
            ],
        ),
    ]
